#!/bin/bash
cd ~/build
git clone https://aur.archlinux.org/$1.git
cd $1
GIT_STATUS=$(git pull)
if [[ "$GIT_STATUS" !=  "Already up to date." ]]; then
	git pull
	makepkg -s
	mv *.tar.zst ../../packages/$1.pkg.tar.zst
fi
